### ISSUE TITLE
KeyError in list-pipelines on Vertex AI

### ISSUE THREAD

**Issue by mwiewior** [getindata/kedro-kubeflow#100]
1. Steps to repoduce:
```bash
kedro kubeflow --env vertex list-pipelines
```
Maybe a simple check on empty list of jobs:
```python
pipelines = self.api_client.list_jobs()["pipelineJobs"]
```
```bash
2022-02-03 15:45:52,895 - kedro_kubeflow.vertex_ai.client - INFO - {}
Traceback (most recent call last):
  File "/home/jupyter/venv/willa-test/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/home/jupyter/venv/willa-test/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 238, in main
    cli_collection()
  File "/home/jupyter/venv/willa-test/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jupyter/venv/willa-test/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 183, in main
    super().main(
  File "/home/jupyter/venv/willa-test/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jupyter/venv/willa-test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jupyter/venv/willa-test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jupyter/venv/willa-test/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jupyter/venv/willa-test/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jupyter/venv/willa-test/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jupyter/venv/willa-test/lib/python3.8/site-packages/kedro_kubeflow/cli.py", line 47, in list_pipelines
    click.echo(context_helper.kfp_client.list_pipelines())
  File "/home/jupyter/venv/willa-test/lib/python3.8/site-packages/kedro_kubeflow/vertex_ai/client.py", line 44, in list_pipelines
    pipelines = self.api_client.list_jobs()["pipelineJobs"]
KeyError: 'pipelineJobs'
```

**Comment by szczeles** [comment]
@mwiewior I think we don't support this operation on Vertex from the beginning, as it doesn't use the same concept of "uploaded pipeline" like Kubeflow does.

**Comment by szczeles** [comment]
@marrrcin Something that you may be interested in, as potential issue for https://github.com/getindata/kedro-vertexai

Closing as not related to kedro-kubeflow. VertexAI support is going to be dropped soon
